<a href="https://colab.research.google.com/github/Kovidapunj/Exploratory-data-analysis-using-python/blob/main/Experiment_14_data_normalisation_and_data_type_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 14
## Title - Data Normalization and data type conversion
(part-A data Normalisation)
## Name - Kovida Punj
## PRN - 25070123063
## Batch - E&TC A3

In [2]:
#dataset
import pandas as pd

data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Unit_Sold':[25,60,35,80,50,15],
    'Discount':[10,15,12,20,18,8],
}
df = pd.DataFrame(data)
df

      Product  Price  Unit_Sold  Discount
0      Laptop  55000         25        10
1      Mobile  20000         60        15
2      Tablet  30000         35        12
3  Headphones   2000         80        20
4  Smartwatch   8000         50        18
5      Camera  45000         15         8

In [3]:
#1. Min-Max Normalisation
df['price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print("\nMin-Max Normalised Price")
print(df[['Product','Price','price_MinMax']])

Min-Max Normalised Price
      Product  Price  price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [4]:
#Normalize multiple columns
cols = ['Price','Unit_Sold','Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print("\nNormalized dataset")
print(df_norm)

Normalized dataset
      Price  Unit_Sold  Discount
0  1.000000   0.153846  0.166667
1  0.339623   0.692308  0.583333
2  0.528302   0.307692  0.333333
3  0.000000   1.000000  1.000000
4  0.113208   0.538462  0.833333
5  0.811321   0.000000  0.000000

In [5]:
#2. Z-Score Normalization
df['Units_Zscore'] = (df['Unit_Sold'] - df['Unit_Sold'].mean()) / df['Unit_Sold'].std()
print("\nZ-Score Normalised Unit_Sold")
print(df[['Product','Unit_Sold','Units_Zscore']])

Z-Score Normalised Unit_Sold
      Product  Unit_Sold  Units_Zscore
0      Laptop         25     -0.799885
1      Mobile         60      0.660775
2      Tablet         35     -0.382554
3  Headphones         80      1.495437
4  Smartwatch         50      0.243443
5      Camera         15     -1.217216

#Part B - Turning categorical variables into quantitative variables in Python

In [6]:
#3. Decimal Scaling
df['Price_Decimal'] = df['Price'] / 100000
print("\nDecimal Scaling")
print(df[['Product','Price','Price_Decimal']])

Decimal Scaling
      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [7]:
import numpy as np
import pandas as pd

data = {
    'order_id':[101,102,103,104,105,106],
    'Customer_Gender': ['Male','Female','Male','Female','Male','Female'],
    'Product_Category':['Electronics','Clothing','home','Electronics','beauty','Books'],
    'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
    'City':['Pune','Mumbai','Delhi','Bangalore','Mumbai','Hyderabad'],
    'Order Value':[4500.32,2300,5400,1200,8000,6500],
}
df = pd.DataFrame(data)
df

,order_id,Customer_Gender,Product_Category,Payment_Method,City,Order Value
0,101,Male,Electronics,UPI,Pune,4500.32
1,102,Female,Clothing,Credit Card,Mumbai,2300.00
2,103,Male,home,Debit Card,Delhi,5400.00
3,104,Female,Electronics,COD,Bangalore,1200.00
4,105,Male,beauty,UPI,Mumbai,8000.00
5,106,Female,Books,Debit Card,Hyderabad,6500.00

In [8]:
#Method 1 : Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
print(df)
#works for only 2 different values

   order_id Customer_Gender Product_Category Payment_Method       City  \
0       101            Male      Electronics            UPI       Pune
1       102          Female         Clothing    Credit Card     Mumbai
2       103            Male             home     Debit Card      Delhi
3       104          Female      Electronics            COD  Bangalore
4       105            Male           beauty            UPI     Mumbai
5       106          Female            Books     Debit Card  Hyderabad

   Order Value  Gender_Label
0      4500.32             1
1      2300.00             0
2      5400.00             1
3      1200.00             0
4      8000.00             1
5      6500.00             0

In [9]:
#Method 2: One-Hot Encoding
df_encoding = pd.get_dummies(df,columns=['Product_Category','Payment_Method','City'])
print(df_encoding)

   order_id Customer_Gender  Order Value  Gender_Label  \
0       101            Male      4500.32             1
1       102          Female      2300.00             0
2       103            Male      5400.00             1
3       104          Female      1200.00             0
4       105            Male      8000.00             1
5       106          Female      6500.00             0

   Product_Category_Books  Product_Category_Clothing  \
0                   False                      False
1                   False                       True
2                   False                      False
3                   False                      False
4                   False                      False
5                    True                      False

   Product_Category_Electronics  Product_Category_beauty  \
0                          True                    False
1                         False                    False
2                         False                    False
3                          True                    False
4                         False                     True
5                         False                    False

   Product_Category_home  Payment_Method_COD  Payment_Method_Credit Card  \
0                  False               False                       False
1                  False               False                        True
2                   True               False                       False
3                  False                True                       False
4                  False               False                       False
5                  False               False                       False

   Payment_Method_Debit Card  Payment_Method_UPI  City_Bangalore  City_Delhi  \
0                      False                True           False       False
1                      False               False           False       False
2                       True               False           False        True
3                      False               False            True       False
4                      False                True           False       False
5                       True               False           False       False

   City_Hyderabad  City_Mumbai  City_Pune
0           False        False       True
1           False         True      False
2           False        False      False
3           False        False      False
4           False         True      False
5            True        False      False

In [15]:
#Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df,columns=['Product_Category','Payment_Method','City'],drop_first=True)
print(df_dummy)

   order_id Customer_Gender  Order Value  Gender_Label  \
0       101            Male      4500.32             1
1       102          Female      2300.00             0
2       103            Male      5400.00             1
3       104          Female      1200.00             0
4       105            Male      8000.00             1
5       106          Female      6500.00             0

   Product_Category_Clothing  Product_Category_Electronics  \
0                      False                          True
1                       True                         False
2                      False                         False
3                      False                          True
4                      False                         False
5                      False                         False

   Product_Category_beauty  Product_Category_home  Payment_Method_Credit Card  \
0                    False                  False                       False
1                    False                  False                        True
2                    False                   True                       False
3                    False                  False                       False
4                     True                  False                       False
5                    False                  False                       False

   Payment_Method_Debit Card  Payment_Method_UPI  City_Delhi  City_Hyderabad  \
0                      False                True       False           False
1                      False               False       False           False
2                       True               False        True           False
3                      False               False       False           False
4                      False                True       False           False
5                       True               False       False            True

   City_Mumbai  City_Pune
0        False       True
1         True      False
2        False      False
3        False      False
4         True      False
5        False      False

In [17]:
import pandas as pd
df = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")

In [18]:
#Min-max normalization
df['price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print("\nMin-Max Normalised Price")
print(df[['Product_ID','Price','price_MinMax']])

Min-Max Normalised Price
   Product_ID  Price  price_MinMax
0        P101    799      0.020243
1        P102   1499      0.048583
2        P103    699      0.016194
3        P104   2499      0.089069
4        P105   3999      0.149798
5        P106   1199      0.036437
6        P107    899      0.024291
7        P108   1899      0.064777
8        P109   5499      0.210526
9        P110    999      0.028340
10       P111   7999      0.311741
11       P112   4599      0.174089
12       P113   1599      0.052632
13       P114    699      0.016194
14       P115    899      0.024291
15       P116   6499      0.251012
16       P117   1199      0.036437
17       P118   1999      0.068826
18       P119   2999      0.109312
19       P120   1299      0.040486
20       P121    499      0.008097
21       P122   2499      0.089069
22       P123   8999      0.352227
23       P124    799      0.020243
24       P125   3499      0.129555
25       P126   4599      0.174089
26       P127  12999      0.514170
27       P128   2199      0.076923
28       P129    699      0.016194
29       P130   1499      0.048583
30       P131   9999      0.392713
31       P132   5999      0.230769
32       P133   3499      0.129555
33       P134  11999      0.473684
34       P135  15999      0.635628
35       P136    599      0.012146
36       P137    799      0.020243
37       P138    299      0.000000
38       P139    999      0.028340
39       P140   1499      0.048583
40       P141   2999      0.109312
41       P142  10999      0.433198
42       P143   4999      0.190283
43       P144  24999      1.000000
44       P145   1999      0.068826
45       P146   7999      0.311741
46       P147  18999      0.757085
47       P148   2499      0.089069
48       P149   3499      0.129555
49       P150    999      0.028340

In [19]:
#2. Z-Score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print("\nZ-Score Normalised Units_Sold")
print(df[['Product_ID','Units_Sold','Units_Zscore']])

Z-Score Normalised Units_Sold
   Product_ID  Units_Sold  Units_Zscore
0        P101         350      0.812282
1        P102         220     -0.260855
2        P103         180     -0.591051
3        P104         410      1.307576
4        P105         520      2.215615
5        P106         390      1.142478
6        P107         140     -0.921247
7        P108         260      0.069341
8        P109         330      0.647184
9        P110         190     -0.508502
10       P111         610      2.958556
11       P112         290      0.316988
12       P113         340      0.729733
13       P114         120     -1.086345
14       P115         200     -0.425953
15       P116         310      0.482086
16       P117         210     -0.343404
17       P118         420      1.390125
18       P119         530      2.298164
19       P120         260      0.069341
20       P121         150     -0.838698
21       P122         310      0.482086
22       P123         170     -0.673600
23       P124         210     -0.343404
24       P125         390      1.142478
25       P126         160     -0.756149
26       P127         140     -0.921247
27       P128         270      0.151890
28       P129         240     -0.095757
29       P130         260      0.069341
30       P131         200     -0.425953
31       P132         180     -0.591051
32       P133         430      1.472674
33       P134         120     -1.086345
34       P135          90     -1.333992
35       P136         160     -0.756149
36       P137         320      0.564635
37       P138         380      1.059929
38       P139         210     -0.343404
39       P140         130     -1.003796
40       P141         150     -0.838698
41       P142         110     -1.168894
42       P143         260      0.069341
43       P144          70     -1.499090
44       P145         310      0.482086
45       P146         200     -0.425953
46       P147         120     -1.086345
47       P148         170     -0.673600
48       P149         150     -0.838698
49       P150         240     -0.095757

In [20]:
#Decimal Scaling
df['Price_Decimal'] = df['Price'] / 100000
df['Reviews_Decimal'] = df['Reviews'] / 100000

print("\nDecimal Scaling")
print(df[['Product_ID','Price','Price_Decimal','Reviews','Reviews_Decimal']])

Decimal Scaling
   Product_ID  Price  Price_Decimal  Reviews  Reviews_Decimal
0        P101    799        0.00799     1520           0.0152
1        P102   1499        0.01499      980           0.0098
2        P103    699        0.00699      870           0.0087
3        P104   2499        0.02499     2100           0.0210
4        P105   3999        0.03999     3050           0.0305
5        P106   1199        0.01199     1750           0.0175
6        P107    899        0.00899      620           0.0062
7        P108   1899        0.01899     1120           0.0112
8        P109   5499        0.05499     1850           0.0185
9        P110    999        0.00999      760           0.0076
10       P111   7999        0.07999     4200           0.0420
11       P112   4599        0.04599     2100           0.0210
12       P113   1599        0.01599     1300           0.0130
13       P114    699        0.00699      540           0.0054
14       P115    899        0.00899      870           0.0087
15       P116   6499        0.06499     2300           0.0230
16       P117   1199        0.01199      760           0.0076
17       P118   1999        0.01999     1600           0.0160
18       P119   2999        0.02999     3500           0.0350
19       P120   1299        0.01299      980           0.0098
20       P121    499        0.00499      420           0.0042
21       P122   2499        0.02499     1450           0.0145
22       P123   8999        0.08999     1250           0.0125
23       P124    799        0.00799      720           0.0072
24       P125   3499        0.03499     2100           0.0210
25       P126   4599        0.04599      980           0.0098
26       P127  12999        0.12999     3100           0.0310
27       P128   2199        0.02199     1300           0.0130
28       P129    699        0.00699      880           0.0088
29       P130   1499        0.01499      990           0.0099
30       P131   9999        0.09999     2100           0.0210
31       P132   5999        0.05999     1750           0.0175
32       P133   3499        0.03499     2500           0.0250
33       P134  11999        0.11999     1450           0.0145
34       P135  15999        0.15999     2100           0.0210
35       P136    599        0.00599      450           0.0045
36       P137    799        0.00799      900           0.0090
37       P138    299        0.00299      600           0.0060
38       P139    999        0.00999      720           0.0072
39       P140   1499        0.01499      520           0.0052
40       P141   2999        0.02999      850           0.0085
41       P142  10999        0.10999     1200           0.0120
42       P143   4999        0.04999     2100           0.0210
43       P144  24999        0.24999     1800           0.0180
44       P145   1999        0.01999     1400           0.0140
45       P146   7999        0.07999     2200           0.0220
46       P147  18999        0.18999     1650           0.0165
47       P148   2499        0.02499      980           0.0098
48       P149   3499        0.03499      870           0.0087
49       P150    999        0.00999      760           0.0076

In [21]:
#Turning categorical variables into quantitative variables
df = pd.read_csv('/content/Student-Dataset.csv')

In [22]:
#Label Encoding-Placement Status
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Placement_Status_Label'] = le.fit_transform(df['Placement_Status'])
df['Gender_Label'] = le.fit_transform(df['Gender'])
print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Status_Label  \
0                     92           Placed  450000                       1
1                     85       Not Placed       0                       0
2                     96           Placed  550000                       1
3                     78       Not Placed       0                       0
4                     88           Placed  480000                       1
5                     72       Not Placed       0                       0
6                     91           Placed  500000                       1
7                     80       Not Placed       0                       0
8                     84           Placed  420000                       1
9                     76       Not Placed       0                       0

   Gender_Label
0             0
1             1
2             0
3             1
4             0
5             1
6             0
7             1
8             0
9             1

In [23]:
#One hot encoding - department
df_encoding = pd.get_dummies(df,columns=['Department'])
print(df_encoding)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_Label  Gender_Label  \
0           Placed  450000                       1             0
1       Not Placed       0                       0             1
2           Placed  550000                       1             0
3       Not Placed       0                       0             1
4           Placed  480000                       1             0
5       Not Placed       0                       0             1
6           Placed  500000                       1             0
7       Not Placed       0                       0             1
8           Placed  420000                       1             0
9       Not Placed       0                       0             1

   Department_Civil  Department_Computer  Department_ENTC  Department_IT  \
0             False                 True            False          False
1             False                False            False           True
2             False                False             True          False
3             False                False            False          False
4             False                 True            False          False
5              True                False            False          False
6             False                False            False           True
7             False                 True            False          False
8             False                False             True          False
9             False                False            False          False

   Department_Mechanical
0                  False
1                  False
2                  False
3                   True
4                  False
5                  False
6                  False
7                  False
8                  False
9                   True

In [24]:
#Dummies - Department
df_dummy = pd.get_dummies(df,columns=['Department'],drop_first=True)
print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_Label  Gender_Label  \
0           Placed  450000                       1             0
1       Not Placed       0                       0             1
2           Placed  550000                       1             0
3       Not Placed       0                       0             1
4           Placed  480000                       1             0
5       Not Placed       0                       0             1
6           Placed  500000                       1             0
7       Not Placed       0                       0             1
8           Placed  420000                       1             0
9       Not Placed       0                       0             1

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True